/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface Category {
  name: string;
  count: number;
}

const Categories: React.FC = () => {
  const categories: Category[] = [
    { name: "Men's Health", count: 9 },
    { name: "Fitness & Exercise", count: 5 },
    { name: "Nutrition & Diet", count: 9 },
    { name: "Healthcare", count: 10 },
    { name: "Technology", count: 3 },
    { name: "Hormonal Health", count: 3 },
    { name: "Mental Health & Well-Being", count: 3 },
    { name: "Lifestyle & Habits", count: 3 },
  ];

  return (
    <aside className="flex flex-col self-stretch my-auto w-full text-base font-medium max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-xl font-semibold leading-none text-neutral-700">
        Categories
      </h2>
      {categories.map((category, index) => (
        <React.Fragment key={index}>
          <div className="flex gap-5 justify-between mt-3.5 text-neutral-700 max-md:max-w-full">
            <div>{category.name}</div>
            <div className="text-right">
              {category.count.toString().padStart(2, "0")}
            </div>
          </div>
          <hr className="shrink-0 mt-1.5 max-w-full h-px border border-teal-500 border-dashed w-[430px]" />
        </React.Fragment>
      ))}
    </aside>
  );
};

export default Categories;
