/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactInfo: React.FC = () => {
  return (
    <>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb4a23546693cb3f4cbb0207ac87c909888d67b1c97f4e6245a95c4ed3802447?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
        className="object-contain shrink-0 my-auto w-0.5 aspect-[0.04]"
        alt=""
      />
      <div className="flex gap-2.5 my-auto leading-5 text-neutral-700">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5c8c3f2fd36c546af613abc01a8c430456e6d6a889db805ed89070a5db060330?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 my-auto aspect-square w-[25px]"
          alt="Location icon"
        />
        <div>
          Ramallah - Al-Manara Roundabout - City Center Building - 5th Floor
        </div>
      </div>
      <div className="flex flex-wrap gap-9 items-start self-start mt-1">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb4a23546693cb3f4cbb0207ac87c909888d67b1c97f4e6245a95c4ed3802447?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 w-0.5 aspect-[0.04]"
          alt=""
        />
        <div className="flex flex-col items-end leading-none text-zinc-500">
          <div>
            Mon - Fri:{" "}
            <span className="font-medium text-neutral-700">
              8:00am - 8:00pm
            </span>
          </div>
          <div className="flex gap-2.5 self-stretch">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b49bbe311cba5dd6884ef2803487cc477778f5c8501e29bd321dfe8ec9d7a7b?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
              className="object-contain shrink-0 aspect-square w-[25px]"
              alt="Clock icon"
            />
            <div className="grow shrink my-auto w-[206px]">
              Saturday:{" "}
              <span className="font-medium text-neutral-700">
                8:30am - 6:00pm
              </span>
            </div>
          </div>
          <div className="max-md:mr-2.5">
            Sunday:{" "}
            <span className="font-medium text-neutral-700">
              9:00am - 5:00pm
            </span>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb4a23546693cb3f4cbb0207ac87c909888d67b1c97f4e6245a95c4ed3802447?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 w-0.5 aspect-[0.04]"
          alt=""
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3568d824283c689e693fbde10ed67cd64a1c183b3cc3335d79d1be93dcfa2b3e?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[25px]"
          alt="Phone icon"
        />
        <div className="leading-5 text-neutral-700">
          059-807-0808 <br /> 052-680-0824 <br /> 02-2921935
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb4a23546693cb3f4cbb0207ac87c909888d67b1c97f4e6245a95c4ed3802447?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 w-0.5 aspect-[0.04]"
          alt=""
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b4091ad400b43bb264dadc39e865cbbaf25839eae07984a3be1c8bd939be2e4a?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 self-stretch my-auto max-w-full aspect-[6.49] w-[156px]"
          alt="Payment methods"
        />
      </div>
    </>
  );
};

export default ContactInfo;
