/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";

const Footer: React.FC = () => {
  return (
    <footer className="flex overflow-hidden flex-col px-20 py-9 mt-40 w-full bg-emerald-50 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between items-end ml-5 max-md:max-w-full">
        <div className="flex flex-col self-stretch max-md:max-w-full">
          <div className="flex gap-5 justify-between max-w-full text-base font-bold text-teal-700 whitespace-nowrap w-[418px]">
            <Logo />
            <div className="self-end mt-8">Contact</div>
          </div>
          <div className="flex gap-5 justify-between self-end mt-3 mr-24 max-w-full w-[263px] max-md:mr-2.5">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/66000eb4081f033e0ffe1a807622cd32c40c2708c0d03ebbb9412b577dbaa3d4?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
              className="object-contain shrink-0 aspect-square w-[25px]"
              alt="Facebook icon"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2fced082844d5a5c9a8a47f268be66fe61e353183213245f0e5d23e09baa2dab?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
              className="object-contain shrink-0 aspect-square w-[25px]"
              alt="Instagram icon"
            />
          </div>
          <div className="max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/e874c2304f7dcd946d8f65b8e3b2af329ef911995fc8e5a098338bb342acc935?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
                  className="object-contain w-full aspect-[2.2] max-md:mt-5"
                  alt="Map"
                />
              </div>
              <div className="flex flex-col ml-5 w-[32%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow text-base leading-none text-zinc-500 max-md:mt-6">
                  <div className="font-medium leading-5 text-neutral-700">
                    Ramallah - Al-Manara Roundabout - City Center Building - 5th
                    Floor
                  </div>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b49bbe311cba5dd6884ef2803487cc477778f5c8501e29bd321dfe8ec9d7a7b?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
                    className="object-contain mt-4 aspect-square w-[25px]"
                    alt="Clock icon"
                  />
                  <div className="mt-1.5">
                    Mon - Fri:{" "}
                    <span className="font-medium text-neutral-700">
                      8:00am - 8:00pm
                    </span>
                  </div>
                  <div className="mt-1.5">
                    Saturday:{" "}
                    <span className="font-medium text-neutral-700">
                      8:30am - 6:00pm
                    </span>
                  </div>
                  <div className="mt-1.5 max-md:mr-2.5">
                    Sunday:{" "}
                    <span className="font-medium text-neutral-700">
                      9:00am - 5:00pm
                    </span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[18%] max-md:ml-0 max-md:w-full">
                <div className="text-base leading-5 text-neutral-700 max-md:mt-5">
                  059-807-0808 <br /> 052-680-0824 <br /> 02-2921935
                </div>
              </div>
            </div>
          </div>
        </div>
        <nav className="flex flex-col items-start mt-8 text-base font-medium text-neutral-700">
          <h3 className="self-stretch font-bold text-teal-700 max-md:mr-1">
            Navigation
          </h3>
          <a href="/" className="mt-5">
            Home
          </a>
          <a href="/about" className="mt-4">
            About Us
          </a>
          <a href="/treatments" className="self-stretch mt-4">
            Treatments
          </a>
          <a href="/faq" className="mt-4">
            FAQ
          </a>
          <a href="/blogs" className="mt-4">
            Blogs
          </a>
        </nav>
        <div className="flex flex-col items-start mt-8 text-base font-medium text-neutral-700">
          <h3 className="font-bold text-teal-700">Services</h3>
          <a href="/booking" className="self-stretch mt-5">
            Booking appointments
          </a>
          <a href="/consultations" className="mt-4">
            Free consultations
          </a>
          <h3 className="mt-2 font-bold text-teal-700">Legal</h3>
          <a href="/terms" className="mt-5">
            Terms & Conditions
          </a>
          <a href="/privacy" className="mt-4">
            Privacy Policy
          </a>
        </div>
      </div>
      <hr className="shrink-0 mt-12 max-w-full h-0.5 border-2 border-teal-700 border-solid w-[1182px] max-md:mt-10 max-md:mr-2" />
      <div className="flex flex-wrap gap-5 justify-between mt-6 text-base font-semibold text-right text-zinc-400 max-md:mr-2 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/347a17afe6a15a890ab1e854cb84a5546a61afbc0c84e2ce4f0830142f0efdc7?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
          className="object-contain shrink-0 max-w-full aspect-[6.49] w-[156px]"
          alt="Payment methods"
        />
        <div>Best Clinic 2024 © All Rights Reserved</div>
      </div>
    </footer>
  );
};

export default Footer;
