/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import ContactInfo from "./ContactInfo";
import Navigation from "./Navigation";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col items-center px-20 pt-5 w-full bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1400px] max-md:max-w-full">
        <div className="flex flex-wrap gap-10 self-start text-base">
          <Logo />
          <ContactInfo />
          <Navigation />
        </div>
      </div>
    </header>
  );
};

export default Header;
