/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero: React.FC = () => {
  return (
    <section className="mt-5">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a084e02f6a88b8429740630be3debf5ecc5f0f771448924a4fd78e05d69bc35?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
        className="object-contain w-full rounded-xl aspect-[2.33] max-md:max-w-full"
        alt="Hero image showcasing the clinic's services"
      />
    </section>
  );
};

export default Hero;
