/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/62073cb1f4add12f89a7a96d93daee14011fe78ad535a3f2a4d24ce26af2a231?placeholderIfAbsent=true&apiKey=d34435c2f52d468e948b79f730126110"
      className="object-contain shrink-0 max-w-full aspect-[2.34] w-[150px]"
      alt="Best Clinic Logo"
    />
  );
};

export default Logo;
